export const CONTAINER_PADDING_X = "px-4 md:px-6";
export const CONTAINER_PADDING_Y = "py-4 md:py-6";
export const ELEMENTS_Y_SPACE = "space-y-4";
export const STICKY_MENU_HEIGHT = "h-14";
export const STICKY_MENU_MARGIN_Y = "my-14";
export const ICON_SIZE_REGULAR = "h-5 w-5";
export const ICON_SIZE_SMALL = "h-4 w-4";
export const MENU_BUTTON_SIZE = "w-12 h-12";
export const TRANSITION_DELAY = 250;
